### ISSUE TITLE
Incorrect httpstatus code 

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#110]
boeing-wave4-knowledgehub/web-analytic-service/src/main/java/com/stackroute/controller/WebAnalyticServiceController.java
catch (Exception e) {
            responseEntity = new ResponseEntity<>("No results found.", HttpStatus.EXPECTATION_FAILED);
            return responseEntity;
        }

**Comment by svnsairam** [comment]
modified HttpStatus
