### ISSUE TITLE
Incorrect HttpStatus code

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#165]
} catch (Exception e) {
            responseEntity = new ResponseEntity<String>("SearchString is not taken.", HttpStatus.BAD_REQUEST);
            return responseEntity;

 catch (Exception e) {
            responseEntity = new ResponseEntity<String>("No results found.", HttpStatus.BAD_REQUEST);
            return responseEntity;
boeing-wave4-knowledgehub/nlp-service/src/main/java/com/stackroute/controller/NlpController.java

**Comment by YKRoshan** [comment]
Done
