### ISSUE TITLE
paragraph-tokeniser: pom.xml: Incorrect parent tag

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#17]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.2.RELEASE</version>
		<relativePath/> 
	</parent>

**Comment by Gauravgkp** [comment]
The same is corrected and updated in git .
