### ISSUE TITLE
remove dead code

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#184]
//    @Autowired
//    private KafkaTemplate<String, JSObject> kafkaTemplate;
//
//    private static final String TOPIC = "FileText";

boeing-wave4-knowledgehub/paragraph-tokenizer/src/main/java/com/stackroute/listener/KafkaConsumer.java

**Comment by Gauravgkp** [comment]
Removed the dead code.
