### ISSUE TITLE
Give proper http status

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#27]
content-extractor/src/main/java/com/stackroute/controller/PdfController.java

 public ResponseEntity<String> getFile(@PathVariable String filename) throws TikaException, SAXException, IOException, FileNotFoundException, EmptyFileException {
            System.out.println(filename);
            try {
                String jsonString = contentExtractionService.extractFromFile(path);
                kafkaTemplate.send(TOPIC,jsonString);
                return ResponseEntity.status(HttpStatus.OK).body(jsonString);

            } catch (Exception e) {
                String message = filename + " is not available";
                return ResponseEntity.status(HttpStatus.CONFLICT).body(message);
            }

**Comment by Komal148** [comment]
Changed Conflict to NOT_FOUND
