### ISSUE TITLE
use appropriate httpstatus code

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave4-knowledgehub#63]
boeing-wave4-knowledgehub/analytic-server/src/main/java/com/stackroute/controller/AnalyticServiceController.java
catch (Exception e) {
            responseEntity = new ResponseEntity<>("No results found.", HttpStatus.BAD_REQUEST);
            return responseEntity;

**Comment by svnsairam** [comment]
Modified to HttpStatus.EXPECTATION_FAILED
